### PR TITLE
errors: reformat pydantic validation error (CRAFT-368)

### PR DESCRIPTION
**Pull request by cmatsuoka**
Change formatting of pydantic errors to be more human-readable. The
new format is similar to the one used in Charmcraft. Specifically,
this changes

```
'foo',1: some error happened
'bar': field required
'baz': extra fields not permitted
```
to
```
- some error happened in field 'foo[1]'
- field 'bar' is required'
- extra field 'baz' not permitted
```
    
Co-authored-by: Chris Patterson <chris.patterson@canonical.com>
Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>

- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Review by cjp256 — APPROVED** [review]
LGTM

**Review by facundobatista — COMMENTED** [review]
Code here looks ok. What bothers me is that we have TWO places where messages are formatted. Here and in the code that uses this lib. Shouldn't the lib just raise the error with proper components and solve the formatting in ONE place? Think of the case of needing to change the formatting, for example, what would happen when this lib is used by several apps?

**Review by sergiusens — APPROVED** [review]
There is nothing wrong with providing a nice error message by default using our current constructs, but I agree with @facundobatista but @cmatsuoka verified that this not intended to be used by Charmcraft itself, just when using craft-parts in isolation

**Comment by cmatsuoka** [comment]
> Code here looks ok. What bothers me is that we have TWO places where messages are formatted. Here and in the code that uses this lib. Shouldn't the lib just raise the error with proper components and solve the formatting in ONE place? Think of the case of needing to change the formatting, for example, what would happen when this lib is used by several apps?

I changed validation handling in the charmcraft craft-parts integration so that charmcraft gets raw errors instead of pre-formatted pydantic validation errors, so now all formatting in the initial validation is performed by charmcraft. The changes in this PR will be used by craft-parts to present errors when running stand-alone or if a validation error happens during the initialization of the lifecycle manager (this should never happen because charmcraft already validated parts).

I'll place this PR on hold until we propose the final craft-parts integration so we can be sure that no errors from craft-parts are leaking during the initial validation (it's harder to verify it with this PR merged because the error messages are in the same style).

**Comment by facundobatista** [comment]
Wonderful
, thanks!

**Pull request merged**
