### PR TITLE
plugins: add kernel plugin implementation

### PR DESCRIPTION
**Pull request by kubiko**
Adding kernel plugin to build kernel snaps from linux kernel source.

Kernel snap is a specific snap for Ubuntu Core which contains kernel binary, firmware, kernel modules, dtbs, initrd
There are various options usually involved, initrd has to be packaged in a specific way and have certain content.
At the same time, many of the steps are common to all the kernel snaps builds. This plugin is trying to streamline this as make kernel snap build easier.

### CODE REVIEW

**Comment by cmatsuoka** [comment]
The kernel plugin seems to be very snap-specific, so we can implement it in Snapcraft as an application plugin instead of adding it directly to craft-parts.

**Comment by kubiko** [comment]
> The kernel plugin seems to be very snap-specific, so we can implement it in Snapcraft as an application plugin instead of adding it directly to craft-parts.

It is indeed very snap-specific. It's a bit confusing for me where snapcraft plugins go at this stage, but since I found most plugins in craft-parts, it was my first shot where to add it :)

**Comment by cmatsuoka** [comment]
> It is indeed very snap-specific. It's a bit confusing for me where snapcraft plugins go at this stage, but since I found most plugins in craft-parts, it was my first shot where to add it :)

See how the colcon and conda plugins are defined in `snapcraft/parts/plugins`, we can define this one there too.

**Comment by facundobatista** [comment]
I concur, this looks more like a Snapcraft plugin that a generic Craft Parts one.

**Comment by kubiko** [comment]
Closing this PR and adding kernel plugin as snapcraft plugin to the existing PR.
Please review it there.
https://github.com/snapcore/snapcraft/pull/3922

**Pull request closed without merging**
