### PR TITLE
fix(plugins): ensure stateless npm plugin

### PR DESCRIPTION
**Pull request by liushuyu**
- [X] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

This pull request works around an issue that regressed NPM-based projects on the Launchpad auto-build system.

The issue was that the Launchpad auto-build system executed pull and build steps separately, thereby losing the shared state between them.

This is a temporary fix for the 1.33 branch.

### CODE REVIEW

**Comment by liushuyu** [comment]
I think I can't fix the linter errors in this hotfix due to too many files affected.

**Comment by tigarmo** [comment]
I confirmed that with this fix the repro case linked in #844 builds locally

**Review by tigarmo — APPROVED** [review]
thanks for the quick fix ✨

**Review by mr-cal — APPROVED** [review]

**Review by cmatsuoka — APPROVED** [review]
Thanks for the quick fix. This should work for now, and we can work on a better solution later (maybe adding infrastructure for plugin-defined state files).

**Pull request merged**
