### PR TITLE
utils: add helpers to read os-release entries

### PR DESCRIPTION
**Pull request by cmatsuoka**
The `os-release` file contains operating system identification data.
Add helpers to obtain information from this file, raising errors
if data could not be retrieved.

This implementation and accompanying tests are a direct port from
`snapcraft.internal.os_release`.

Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>

- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Review by sergiusens — APPROVED** [review]
I know this is almost a copy of Snapcraft but we should add a note to consolidate the strategy here for craft-providers and charmcraft.

**Comment by cmatsuoka** [comment]
> I know this is almost a copy of Snapcraft but we should add a note to consolidate the strategy here for craft-providers and charmcraft.

Perhaps spin it off as a stand-alone utility package outside crafts?

**Comment by cmatsuoka** [comment]
Close and reopen to restart tests.

**Comment by sergiusens** [comment]
El miércoles, 28 de abril de 2021 09:13:02 -03 Claudio Matsuoka escribió:
> > I know this is almost a copy of Snapcraft but we should add a note to
> > consolidate the strategy here for craft-providers and charmcraft.
> Perhaps spin it off as a stand-alone utility package outside crafts?

Yeah, this :-)

**Pull request merged**
