### PR TITLE
packages: interface to configure apt (CRAFT-376)

### PR DESCRIPTION
**Pull request by cjp256**
Refactor apt_cache() to expose all performed configuration for
apt when using stage-packages in an extensible manner.  Set
defaults that match the current current behavior.

Future work may change the defaults and remove the unnecessary
re-configuration of apt (needs only be done once per-process).

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>

- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Review by sergiusens — CHANGES_REQUESTED** [review]
I think the point was to make this independent of $SNAP as that can lead to spurious errors, the defaults could just be None and it is up to the application to change that. If we still want to use and environment variable, we should use a different one, something like CRAFT_PARTS_REPO_ROOT that the application should set

**Comment by cjp256** [comment]
> I think the point was to make this independent of $SNAP as that can lead to spurious errors, the defaults could just be None and it is up to the application to change that. If we still want to use and environment variable, we should use a different one, something like CRAFT_PARTS_REPO_ROOT that the application should set

I constrained this PR to match existing behavior by default (with some sanity checks) so it is evident that this refactoring doesn't change behavior.  I plan a short follow up to selectively change defaults as needed.  However, each application should define their own AptStagePackageOptions.

The last bit on my TODO is to decide whether to make the default AptStagePackageOptions global, static to AptCache, or provide an interface to set/get the default (e.g. via lifecycle manager).  I'd like to have a quick chat about it first before making that change.

**Comment by cmatsuoka** [comment]
I'm not a big fan of using an environment variable because it would be the only configuration done that way, with all other configuration parameters passed when creating the lifecycle manager. `PARTS_*` environment variables do exist, but they're mostly used internally (e.g. to set the ctl fifo path).

**Comment by cmatsuoka** [comment]
Also it's interesting to create this configuration API considering that repo/packages will be made into a separate craft project at some point.

**Comment by sergiusens** [comment]
We are going with the application_name concept, we can revisit this when looking closer at craft-repo

**Comment by cmatsuoka** [comment]
Oops. Reopened the wrong PR.

**Pull request closed without merging**
