### PR TITLE
link to common part properties

### PR DESCRIPTION
**Pull request by yanksyoon**
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Comment by yanksyoon** [comment]
I've signed the CLA a bit later than the CI :/ retriggering should fix it.

**Review by dariuszd21 — APPROVED** [review]
Thank you!

**Comment by tigarmo** [comment]
@yanksyoon the cla-check is still failing, did you add your Github account when signing the agreement?

**Comment by yanksyoon** [comment]
@tigarmo I have signed the CLA using the following details (which seems correct to me), I've just tried signing it again. Would you be able to try it again please?
image

**Comment by yanksyoon** [comment]
@tigarmo Hi! The lint seems to be failing here for an unrelated change, would you mind help re-triggering the workflow please? Thank you!

**Comment by mr-cal** [comment]
@yanksyoon, I'll fix those linter failures in a separate PR and then we will land this PR afterwards.

**Pull request merged**
