### PR TITLE
requirements: pin urllib3 version to prevent request problems

### PR DESCRIPTION
**Pull request by cmatsuoka**
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Review by lengau — APPROVED** [review]
Looks like this is related to `requests_unixsocket` and someone has opened a PR on it: https://github.com/msabramo/requests-unixsocket/pull/69

Could you include that link in the comment so it's easy in future to see why we pinned urllib3 <2.?

**Comment by syu-w** [comment]
Maybe we can stop use that `pyxdg` package?

**Comment by lengau** [comment]
@syu-w probably... The project seems to be pretty inactive on freedesktop.org (https://gitlab.freedesktop.org/xdg/pyxdg), so I'm not sure whether it's considered actively maintained. The lack of response from maintainers on pull requests leads me towards thinking it's not, but I've [bumped the xdg mailing list](https://lists.freedesktop.org/archives/xdg/2023-May/014655.html) about it. 

For what we use it for, implementing the standard directly ourselves probably wouldn't be that bad, but from a "health of the community" perspective I'd rather see the package updated.

**Comment by cmatsuoka** [comment]
Also including the xdg pyright workaround to avoid dependency deadlock.

**Pull request merged**
